#!/bin/bash

# Disallowed email domains and addresses
DISALLOWED_EMAILS=("gmail.com" "yahoo.com" "outlook.com" "hotmail.com" "aol.com" "icloud.com" "noreply@github.com" "github.com")

# Get the email of the commit author
commit_author_email=$(git config user.email)

# Validate commit author's email against disallowed emails
for email in "${DISALLOWED_EMAILS[@]}"; do
    if [[ $commit_author_email == *"$email"* ]]; then
        echo ""
        echo "commit_author_email: $commit_author_email"
        echo "Disallowed email or domain found in commit author's email: $email"
        echo ""
	echo "Please correct your committer email using the below commands"
	echo ""
	echo -e "Please run the below command to set the email globally:\n git config --global user.email <your-email>@<your-organisation>.com \n"
	echo -e "If You want to set up committer email only for this repository, then please run the comand without --global flag: \n git config user.email <your-email>@<your-organisation>.com \n"
        exit 1
    fi
done

rm -rf /tmp/gitleaks.toml
curl -o /tmp/gitleaks.toml https://raw.githubusercontent.com/ksripraveena/Test_Gitleaks/main/gitleaks.toml

printf "\n\e[1;31mTo mark any identified key as False Positive or business requirement, Please run the below command by adding the fingerprint value of the respective issue and please report this to security team to add to the exclusion list\e[0m\n" 

printf "\n\e[1;31m Command : '<Fingerprint>' >> .gitleaksignore   \e[0m\n"

printf "\n\e[1;31m Example : 749ce09a83b1f6f25d9d2b7e6aad61cbfe16d2cf:taskManager/settings.py:aws-access-token:19 >> .gitleaksignore   \e[0m\n\n"

touch .gitleaksignore
ls -lah
gitleaks detect --source . --config /tmp/gitleaks.toml  -v

exit 0
